site_name: werewolf

nav:
    - Home: index.md
    - Quick Start: quick-start.md
    - Contributing: contributing.md

theme: gitbook

repo_url: https://github.com/Descent098/werewolf

site_description: A web version of the game werewolf implemented in python using flask

site_author: Kieran Wood
